PAHFIT/pahfit

pahfit/base.py
scripts/run_pahfit

This PR fixes the split index bug. Now pahfit will run for all ipac input spectra without errors. However, txt/ascii formats will still raise an error due to either the 'txt' extension or absence of units in the header.

split index fix

---

pahfit/base.py
pahfit/component_models.py

Replacing Drude1D with Astropy's Drude1D class. Fitting M101_Nucleus_irs.ipac returns identical output results and plot, giving the following warnings:
"WARNING: AstropyDeprecationWarning: Class BlackBody1D defines class attributes ``inputs``.
This has been deprecated in v4.0 and support will be removed in v4.1.
Starting with v4.0 classes must define a class attribute ``n_inputs``.
Please consult the documentation for details.
[astropy.modeling.core]
WARNING: AstropyDeprecationWarning: Class BlackBody1D defines class attributes ``inputs``.
This has been deprecated in v4.0 and support will be removed in v4.1.
Starting with v4.0 classes must define a class attribute ``n_inputs``.
Please consult the documentation for details.
[astropy.modeling.core]
WARNING: AstropyDeprecationWarning: Class …

Local Drude1D class replaced by Astropy's Drude1D

---

tox.ini

One more line of code needed for codecov to work.

coverage report generation code

---

pahfit/component_models.py

The original silicate attenuation curve was not well stitched at ~12 um. This pull request fixes the issue.

Fix glitch at 12 um in silicate attenuation curve

---

pahfit/base.py
pahfit/tests/test_classic_pack.py
scripts/run_pahfit

Adding the function -- starting_point in base.py, which takes the input spectrum and guesses the starting points of the components' amplitude, based on the suggestions in #82. Note that this function will not be applied if amp_fixed in each component is set to be True in the science pack file.

Add starting point

---

scripts/run_pahfit

For v2.0, the goal is to have the python version to be very similar to the IDL version.  One area for this is the parameters that impact the quality and speed of the fit.  Read the doc for [mpfitfun.pro](https://pages.physics.wisc.edu/~craigm/idl/down/mpfitfun.pro) and the docs for the astropy [LevMarLSQFitter](https://docs.astropy.org/en/stable/api/astropy.modeling.fitting.LevMarLSQFitter.html) and the called the scipy [leastsq](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq).  To my understanding the max number of iterations (200) and tolerances (1e-10) needed to be set.
Closes #84.

Fit parameters to match IDL mpfitfun

---

pahfit/base.py
pahfit/component_models.py
scripts/plot_pahfit

In guess and the S07_att component, switch from spline interpolation to a more simple linear interpolation.  This fixes a bug in fitting the NGC 2023.  The NGC 2023 spectrum looked fine.  No idea why the spline interpolation didn't work (maybe something about the wavelength spacing of the spectrum?).  But simple linear interpolation should be fine.
Closes #97.
Also fixed a minor bug in plot_pahfit to update it to include passing the observed spectrum when defining the PAHFIT model.

Switch to simple scipy.interpolate.interp1d interpolation 

---

pahfit/scripts/plot_pahfit.py
pahfit/scripts/run_pahfit.py
setup.cfg

Make the `run_pahfit` and `plot_pahfit` scripts callable system wide after pip install.  This uses entry-points.  This restores the previous behavior that had these scripts installed system wide using a different method.  Entry-points are more pythonic (I think) and supported with the new packaging files.  This means our current docs for the example running and plotting of results are now correct again.  Locations of the scripts moved to inside the pahfit directory to allow entry-points to work.
Closes #106.

Scripts now callable system wide after pip install

---

pahfit/base.py

Fixed the placement of param_info[x]['amps'][i] = amp_guess for BBs and its indentation for the rest of the parameters. Now the estimate function will work only for non-fixed amplitudes.

Indentation and param_Info placement fix

---

pahfit/base.py

This PR fixes a double entry of the right side attenuation axis introduced after PR #115 merge. This was caused because I included the right side attenuation axis code (introduced in PR #114) independently in PR #115, because PR #115 was created from a branch before the merge of PR #114. 
Probably this is an example where things can be tricky with multiple pending PRs.

Fix right axis

---

docs/fit_spectrum.rst

Changed wording of the paragraph explaining how to fit an example using `run_pahfit` and the `M101_Nucleus_irs.ipac` example file.

Update fit_spectrum.rst to clarify where example data can be found

---

pahfit/component_models.py

Fixed typo:
Kemper, Vriend, & Tielens instead of Kemper, Vreind, & Tielens.

fixed typo in article ref in component_models.py

---

pahfit/scripts/run_pahfit.py

Replacing `estimate_start` with `no_starting_estimate` argument, to bypass the start point estimation if needed when fitting.

replace estimate_start with no_starting_estimate

---

pahfit/base.py
pahfit/feature_strengths.py
pahfit/scripts/run_pahfit.py

This PR should replace #141. 
Differences with #141:
- New separate module `feature_strengths.py` now called to calculate PAH feature and emission line strengths.
- Profile-weighted uncertainties removed, but output table uncertainty entry kept (empty) as placeholder for future implementation.
- New argument in `run_pahfit` (`--strength_calc`) which will enable feature strength calculation when provided.

Estimate feature strengths

---

docs/file_formats.rst
docs/index.rst

Added "intrinsic" or "unattenuated" to amplitudes of BB and features (issue 130)
Added comment that we use astropy Gaussian1D and Drude1D + link (issue 122)
Added comment stating IDL PAHFIT uses fractional FWHM while here we use FWHM
for Drude profiles (issue 152). We can update this if we decide to change it.

small changes to docs

---

.github/workflows/tex-tests.yml
tox.ini

python 3.6 no longer allowed.  python 3.7 old as well.  Moving tests to newer version of python, numpy, and astropy.  Based on current astropy tox.ini.

updating test versions

---

pahfit/base.py

This is a simple fix for the overly generous 2x FWHM (see #174), which led to spurious fits.  This simply hard-codes the 10% for now.  In the near term, we plan to implement a new Instrument Pack/Science Pack with generator, making this code irrelevant.

Simple FWHM Fix

---

pahfit/errors.py
pahfit/packs/instrument.py
pahfit/packs/instrument/spitzer.yaml

This supports fitting stitched spectra by allowing the user to specify an iterable of instruments instead of just a single value per input spectrum:
``` python
ins=("jwst.miri.mrs.ch1.A","jwst.miri.mrs.ch1.B")
```
and/or glob-style match strings:
``` python
ins="jwst.miri.mrs.ch*.[AB]"
```
It works by identifying all overlapping instrument segments at the given wavelengths, computing all relevant resolutions, and using the _average_ value with lower and upper bounds set to the min and max predicted resolution.  Lines which intersect only one segment have masked bounds (i.e., are fixed).
Note that, if multiple segments are provided or matched:
1. the return value of `wave_ranges()` can be a list of (2-element) lists.
2. `fwhm()` and `resolution()` return `(n, 3)` _masked_ arrays (given `n` …

Multi + glob-style instrument specification for stitched spectra fitting

---

pahfit/packs/instrument.py
pahfit/packs/instrument/jwst.yaml

NISPEC polynomial fits to resolution had implicit 'domain' set from
numpy.polynomial.Polynomial.  The domain was not saved, so evaluating
the polynomial led to differet results.  All segments were re-fit with
default ([-1,1]) domain, except for prism, which did not converge
without wavelength rescaling due to unusual shape.  Direct support of
domain was added.
Please check against published resolution results. Closes #235.

Fix nirspec resolution

---

pahfit/helpers.py
pahfit/tests/test_included_spectra.py
setup.cfg

I found that the specutils reader doesn't care if the columns are named 'sigma' or 'stddev'. So just by changing the reader to Spectrum1D, we can now read in all our included spectra.
I also added a test for this read-in step. It was already useful to iron out some bugs and convince myself that this will work for everything we need. Should be useful in the future too, when new example spectra get added.

read_spectrum as a wrapper around Spectrum1D.read

---

pahfit/base.py
pahfit/model.py
pahfit/tests/test_model_impl.py

Adresses #248. I have not yet put in the suggested "components" option. The logic might be a bit complex once something like that is added.
Other things to note
- "wavelengths" and "spec" are separate keyword arguments. Spec is used for BOTH the wavelengths and the flux unit. "wavelengths" overrides the wavelengths of "spec". If none of the two are provided, I use a grid based on the wavelength range and fwhm of the instruments.
- Without having a reference spectrum, it's impossible to know what the flux units are (unless we store them from the last fit). For now, I resorted to the following behaviour:
+ "flux_unit" option overrides anything else
+ flux unit is derived from spec when provided
+ flux unit set to dimensionless when nothing else available
- "redshift": the provided …

Tabulate model spectrum

---

pahfit/features/features.py
pahfit/helpers.py
pahfit/model.py
pahfit/units.py

This includes the exact same commits as #259 , but adds a few extra changes
- Units for 'power' columns. Set to 'amplitude units' for now, i.e. `units.intensity` or MJy / sr. After the "power gaussian" and "power drude" have been implemented, we will switch this to `units.intensity_power`
- error message that makes clear that only units compatible with MJy / sr are supported 
- conversion of the spectrum and wavelengths to internal units when the user input is parsed

Standardize units (extended)

---

pahfit/features/features.py
pahfit/features/features_format.py
pahfit/features/util.py

Partially masked arrays are not really well supported, and required elaborate workarounds for pretty printing.  Here we switch to using a _structured_ array type (`val`, `min`, `max` fields),  and represent "fixed" bounds with a pair of `np.nan` values for `min` and `max`,  _instead of_ masking them.  I.e. `nan` is interpreted as the same as negative or positive infinity, unless both bounds are `nan`, which indicates a fixed parameter.   
"Fully open" (unconstrained) bounds are expressed just as before, with `(-np.inf, np.inf)`.  But in general: don't do those ;).

Simplify feature bounds using np.nan instead of masking
